variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "availability_zone1" {}
variable "availability_zone2" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr1" {}
variable "public_subnet_cidr2" {}
variable "private_subnet_cidr1" {}
variable "private_subnet_cidr2" {}
variable "hamgmt_subnet_cidr1" {}
variable "hamgmt_subnet_cidr2" {}
variable "tgwattach_subnet_cidr1" {}
variable "tgwattach_subnet_cidr2" {}
variable "fgt1_eni1_id" {}
variable "tag_name_prefix" {}
variable "tag_name_unique" {}
variable "tgw_creation" {}
variable "transit_gateway_id" {}
variable "tgw_security_route_table_id" {}
variable "tgw_spoke_route_table_id" {}